declare namespace RageEnums {
	/** [https://wiki.rage.mp/index.php?title=Sounds](https://wiki.rage.mp/index.php?title=Sounds) */
	const enum Alarms {
		AGENCY_HEIST_FIB_TOWER_ALARMS = 'AGENCY_HEIST_FIB_TOWER_ALARMS',
		AGENCY_HEIST_FIB_TOWER_ALARMS_UPPER = 'AGENCY_HEIST_FIB_TOWER_ALARMS_UPPER',
		AGENCY_HEIST_FIB_TOWER_ALARMS_UPPER_B = 'AGENCY_HEIST_FIB_TOWER_ALARMS_UPPER_B',
		BIG_SCORE_HEIST_VAULT_ALARMS = 'BIG_SCORE_HEIST_VAULT_ALARMS',
		FBI_01_MORGUE_ALARMS = 'FBI_01_MORGUE_ALARMS',
		FIB_05_BIOTECH_LAB_ALARMS = 'FIB_05_BIOTECH_LAB_ALARMS',
		JEWEL_STORE_HEIST_ALARMS = 'JEWEL_STORE_HEIST_ALARMS',
		PALETO_BAY_SCORE_ALARM = 'PALETO_BAY_SCORE_ALARM',
		PALETO_BAY_SCORE_CHICKEN_FACTORY_ALARM = 'PALETO_BAY_SCORE_CHICKEN_FACTORY_ALARM',
		PORT_OF_LS_HEIST_FORT_ZANCUDO_ALARMS = 'PORT_OF_LS_HEIST_FORT_ZANCUDO_ALARMS',
		PORT_OF_LS_HEIST_SHIP_ALARMS = 'PORT_OF_LS_HEIST_SHIP_ALARMS',
		PRISON_ALARMS = 'PRISON_ALARMS',
		PROLOGUE_VAULT_ALARMS = 'PROLOGUE_VAULT_ALARMS'
	}
}
