declare namespace RageEnums.Hud {
	/** [https://wiki.rage.mp/index.php?title=Fonts_and_Colors](https://wiki.rage.mp/index.php?title=Fonts_and_Colors) */
	const enum Colors {
		/** ![FFFFFF](https://htmlcolors.com/color-image/FFFFFF.png) */
		PURE_WHITE = 'HUD_COLOUR_PURE_WHITE',
		/** ![F0F0F0](https://htmlcolors.com/color-image/F0F0F0.png) */
		WHITE = 'HUD_COLOUR_WHITE',
		/** ![000000](https://htmlcolors.com/color-image/000000.png) */
		BLACK = 'HUD_COLOUR_BLACK',
		/** ![9B9B9B](https://htmlcolors.com/color-image/9B9B9B.png) */
		GREY = 'HUD_COLOUR_GREY',
		/** ![CDCDCD](https://htmlcolors.com/color-image/CDCDCD.png) */
		GREYLIGHT = 'HUD_COLOUR_GREYLIGHT',
		/** ![4D4D4D](https://htmlcolors.com/color-image/4D4D4D.png) */
		GREYDARK = 'HUD_COLOUR_GREYDARK',
		/** ![E03232](https://htmlcolors.com/color-image/E03232.png) */
		RED = 'HUD_COLOUR_RED',
		/** ![F09999](https://htmlcolors.com/color-image/F09999.png) */
		REDLIGHT = 'HUD_COLOUR_REDLIGHT',
		/** ![701919](https://htmlcolors.com/color-image/701919.png) */
		REDDARK = 'HUD_COLOUR_REDDARK',
		/** ![5DB6E5](https://htmlcolors.com/color-image/5DB6E5.png) */
		BLUE = 'HUD_COLOUR_BLUE',
		/** ![AEDBF2](https://htmlcolors.com/color-image/AEDBF2.png) */
		BLUELIGHT = 'HUD_COLOUR_BLUELIGHT',
		/** ![2F5C73](https://htmlcolors.com/color-image/2F5C73.png) */
		BLUEDARK = 'HUD_COLOUR_BLUEDARK',
		/** ![F0C850](https://htmlcolors.com/color-image/F0C850.png) */
		YELLOW = 'HUD_COLOUR_YELLOW',
		/** ![FEEBA9](https://htmlcolors.com/color-image/FEEBA9.png) */
		YELLOWLIGHT = 'HUD_COLOUR_YELLOWLIGHT',
		/** ![7E6B29](https://htmlcolors.com/color-image/7E6B29.png) */
		YELLOWDARK = 'HUD_COLOUR_YELLOWDARK',
		/** ![FF8555](https://htmlcolors.com/color-image/FF8555.png) */
		ORANGE = 'HUD_COLOUR_ORANGE',
		/** ![FFC2AA](https://htmlcolors.com/color-image/FFC2AA.png) */
		ORANGELIGHT = 'HUD_COLOUR_ORANGELIGHT',
		/** ![7F422A](https://htmlcolors.com/color-image/7F422A.png) */
		ORANGEDARK = 'HUD_COLOUR_ORANGEDARK',
		/** ![72CC72](https://htmlcolors.com/color-image/72CC72.png) */
		GREEN = 'HUD_COLOUR_GREEN',
		/** ![B9E6B9](https://htmlcolors.com/color-image/B9E6B9.png) */
		GREENLIGHT = 'HUD_COLOUR_GREENLIGHT',
		/** ![396639](https://htmlcolors.com/color-image/396639.png) */
		GREENDARK = 'HUD_COLOUR_GREENDARK',
		/** ![8466E2](https://htmlcolors.com/color-image/8466E2.png) */
		PURPLE = 'HUD_COLOUR_PURPLE',
		/** ![C0B3EF](https://htmlcolors.com/color-image/C0B3EF.png) */
		PURPLELIGHT = 'HUD_COLOUR_PURPLELIGHT',
		/** ![43396F](https://htmlcolors.com/color-image/43396F.png) */
		PURPLEDARK = 'HUD_COLOUR_PURPLEDARK',
		/** ![CB3694](https://htmlcolors.com/color-image/CB3694.png) */
		PINK = 'HUD_COLOUR_PINK',
		/** ![359A47](https://htmlcolors.com/color-image/359A47.png) */
		RADAR_HEALTH = 'HUD_COLOUR_RADAR_HEALTH',
		/** ![5DB6E5](https://htmlcolors.com/color-image/5DB6E5.png) */
		RADAR_ARMOUR = 'HUD_COLOUR_RADAR_ARMOUR',
		/** ![EB2427](https://htmlcolors.com/color-image/EB2427.png) */
		RADAR_DAMAGE = 'HUD_COLOUR_RADAR_DAMAGE',
		/** ![C25050](https://htmlcolors.com/color-image/C25050.png) */
		NET_PLAYER1 = 'HUD_COLOUR_NET_PLAYER1',
		/** ![9C6EAF](https://htmlcolors.com/color-image/9C6EAF.png) */
		NET_PLAYER2 = 'HUD_COLOUR_NET_PLAYER2',
		/** ![FF7BC4](https://htmlcolors.com/color-image/FF7BC4.png) */
		NET_PLAYER3 = 'HUD_COLOUR_NET_PLAYER3',
		/** ![F79F7B](https://htmlcolors.com/color-image/F79F7B.png) */
		NET_PLAYER4 = 'HUD_COLOUR_NET_PLAYER4',
		/** ![B29084](https://htmlcolors.com/color-image/B29084.png) */
		NET_PLAYER5 = 'HUD_COLOUR_NET_PLAYER5',
		/** ![8DCEA7](https://htmlcolors.com/color-image/8DCEA7.png) */
		NET_PLAYER6 = 'HUD_COLOUR_NET_PLAYER6',
		/** ![71A9AF](https://htmlcolors.com/color-image/71A9AF.png) */
		NET_PLAYER7 = 'HUD_COLOUR_NET_PLAYER7',
		/** ![D3D1E7](https://htmlcolors.com/color-image/D3D1E7.png) */
		NET_PLAYER8 = 'HUD_COLOUR_NET_PLAYER8',
		/** ![907F99](https://htmlcolors.com/color-image/907F99.png) */
		NET_PLAYER9 = 'HUD_COLOUR_NET_PLAYER9',
		/** ![6AC4BF](https://htmlcolors.com/color-image/6AC4BF.png) */
		NET_PLAYER10 = 'HUD_COLOUR_NET_PLAYER10',
		/** ![D6C499](https://htmlcolors.com/color-image/D6C499.png) */
		NET_PLAYER11 = 'HUD_COLOUR_NET_PLAYER11',
		/** ![EA8E50](https://htmlcolors.com/color-image/EA8E50.png) */
		NET_PLAYER12 = 'HUD_COLOUR_NET_PLAYER12',
		/** ![98CBEA](https://htmlcolors.com/color-image/98CBEA.png) */
		NET_PLAYER13 = 'HUD_COLOUR_NET_PLAYER13',
		/** ![B26287](https://htmlcolors.com/color-image/B26287.png) */
		NET_PLAYER14 = 'HUD_COLOUR_NET_PLAYER14',
		/** ![908E7A](https://htmlcolors.com/color-image/908E7A.png) */
		NET_PLAYER15 = 'HUD_COLOUR_NET_PLAYER15',
		/** ![A6755E](https://htmlcolors.com/color-image/A6755E.png) */
		NET_PLAYER16 = 'HUD_COLOUR_NET_PLAYER16',
		/** ![AFA8A8](https://htmlcolors.com/color-image/AFA8A8.png) */
		NET_PLAYER17 = 'HUD_COLOUR_NET_PLAYER17',
		/** ![E88E9B](https://htmlcolors.com/color-image/E88E9B.png) */
		NET_PLAYER18 = 'HUD_COLOUR_NET_PLAYER18',
		/** ![BBD65B](https://htmlcolors.com/color-image/BBD65B.png) */
		NET_PLAYER19 = 'HUD_COLOUR_NET_PLAYER19',
		/** ![0C7B56](https://htmlcolors.com/color-image/0C7B56.png) */
		NET_PLAYER20 = 'HUD_COLOUR_NET_PLAYER20',
		/** ![7BC4FF](https://htmlcolors.com/color-image/7BC4FF.png) */
		NET_PLAYER21 = 'HUD_COLOUR_NET_PLAYER21',
		/** ![AB3CE6](https://htmlcolors.com/color-image/AB3CE6.png) */
		NET_PLAYER22 = 'HUD_COLOUR_NET_PLAYER22',
		/** ![CEA90D](https://htmlcolors.com/color-image/CEA90D.png) */
		NET_PLAYER23 = 'HUD_COLOUR_NET_PLAYER23',
		/** ![4763AD](https://htmlcolors.com/color-image/4763AD.png) */
		NET_PLAYER24 = 'HUD_COLOUR_NET_PLAYER24',
		/** ![2AA6B9](https://htmlcolors.com/color-image/2AA6B9.png) */
		NET_PLAYER25 = 'HUD_COLOUR_NET_PLAYER25',
		/** ![BA9D7D](https://htmlcolors.com/color-image/BA9D7D.png) */
		NET_PLAYER26 = 'HUD_COLOUR_NET_PLAYER26',
		/** ![C9E1FF](https://htmlcolors.com/color-image/C9E1FF.png) */
		NET_PLAYER27 = 'HUD_COLOUR_NET_PLAYER27',
		/** ![F0F096](https://htmlcolors.com/color-image/F0F096.png) */
		NET_PLAYER28 = 'HUD_COLOUR_NET_PLAYER28',
		/** ![ED8CA1](https://htmlcolors.com/color-image/ED8CA1.png) */
		NET_PLAYER29 = 'HUD_COLOUR_NET_PLAYER29',
		/** ![F98A8A](https://htmlcolors.com/color-image/F98A8A.png) */
		NET_PLAYER30 = 'HUD_COLOUR_NET_PLAYER30',
		/** ![FCEFA6](https://htmlcolors.com/color-image/FCEFA6.png) */
		NET_PLAYER31 = 'HUD_COLOUR_NET_PLAYER31',
		/** ![F0F0F0](https://htmlcolors.com/color-image/F0F0F0.png) */
		NET_PLAYER32 = 'HUD_COLOUR_NET_PLAYER32',
		/** ![9FC9A6](https://htmlcolors.com/color-image/9FC9A6.png) */
		SIMPLEBLIP_DEFAULT = 'HUD_COLOUR_SIMPLEBLIP_DEFAULT',
		/** ![8C8C8C](https://htmlcolors.com/color-image/8C8C8C.png) */
		MENU_BLUE = 'HUD_COLOUR_MENU_BLUE',
		/** ![8C8C8C](https://htmlcolors.com/color-image/8C8C8C.png) */
		MENU_GREY_LIGHT = 'HUD_COLOUR_MENU_GREY_LIGHT',
		/** ![282828](https://htmlcolors.com/color-image/282828.png) */
		MENU_BLUE_EXTRA_DARK = 'HUD_COLOUR_MENU_BLUE_EXTRA_DARK',
		/** ![F0A000](https://htmlcolors.com/color-image/F0A000.png) */
		MENU_YELLOW = 'HUD_COLOUR_MENU_YELLOW',
		/** ![F0A000](https://htmlcolors.com/color-image/F0A000.png) */
		MENU_YELLOW_DARK = 'HUD_COLOUR_MENU_YELLOW_DARK',
		/** ![F0A000](https://htmlcolors.com/color-image/F0A000.png) */
		MENU_GREEN = 'HUD_COLOUR_MENU_GREEN',
		/** ![8C8C8C](https://htmlcolors.com/color-image/8C8C8C.png) */
		MENU_GREY = 'HUD_COLOUR_MENU_GREY',
		/** ![3C3C3C](https://htmlcolors.com/color-image/3C3C3C.png) */
		MENU_GREY_DARK = 'HUD_COLOUR_MENU_GREY_DARK',
		/** ![1E1E1E](https://htmlcolors.com/color-image/1E1E1E.png) */
		MENU_HIGHLIGHT = 'HUD_COLOUR_MENU_HIGHLIGHT',
		/** ![8C8C8C](https://htmlcolors.com/color-image/8C8C8C.png) */
		MENU_STANDARD = 'HUD_COLOUR_MENU_STANDARD',
		/** ![4B4B4B](https://htmlcolors.com/color-image/4B4B4B.png) */
		MENU_DIMMED = 'HUD_COLOUR_MENU_DIMMED',
		/** ![323232](https://htmlcolors.com/color-image/323232.png) */
		MENU_EXTRA_DIMMED = 'HUD_COLOUR_MENU_EXTRA_DIMMED',
		/** ![5F5F5F](https://htmlcolors.com/color-image/5F5F5F.png) */
		BRIEF_TITLE = 'HUD_COLOUR_BRIEF_TITLE',
		/** ![646464](https://htmlcolors.com/color-image/646464.png) */
		MID_GREY_MP = 'HUD_COLOUR_MID_GREY_MP',
		/** ![5D2727](https://htmlcolors.com/color-image/5D2727.png) */
		NET_PLAYER1_DARK = 'HUD_COLOUR_NET_PLAYER1_DARK',
		/** ![4D3759](https://htmlcolors.com/color-image/4D3759.png) */
		NET_PLAYER2_DARK = 'HUD_COLOUR_NET_PLAYER2_DARK',
		/** ![7C3E63](https://htmlcolors.com/color-image/7C3E63.png) */
		NET_PLAYER3_DARK = 'HUD_COLOUR_NET_PLAYER3_DARK',
		/** ![785050](https://htmlcolors.com/color-image/785050.png) */
		NET_PLAYER4_DARK = 'HUD_COLOUR_NET_PLAYER4_DARK',
		/** ![574842](https://htmlcolors.com/color-image/574842.png) */
		NET_PLAYER5_DARK = 'HUD_COLOUR_NET_PLAYER5_DARK',
		/** ![4A6753](https://htmlcolors.com/color-image/4A6753.png) */
		NET_PLAYER6_DARK = 'HUD_COLOUR_NET_PLAYER6_DARK',
		/** ![3C5558](https://htmlcolors.com/color-image/3C5558.png) */
		NET_PLAYER7_DARK = 'HUD_COLOUR_NET_PLAYER7_DARK',
		/** ![696940](https://htmlcolors.com/color-image/696940.png) */
		NET_PLAYER8_DARK = 'HUD_COLOUR_NET_PLAYER8_DARK',
		/** ![483F4C](https://htmlcolors.com/color-image/483F4C.png) */
		NET_PLAYER9_DARK = 'HUD_COLOUR_NET_PLAYER9_DARK',
		/** ![35625F](https://htmlcolors.com/color-image/35625F.png) */
		NET_PLAYER10_DARK = 'HUD_COLOUR_NET_PLAYER10_DARK',
		/** ![6B624C](https://htmlcolors.com/color-image/6B624C.png) */
		NET_PLAYER11_DARK = 'HUD_COLOUR_NET_PLAYER11_DARK',
		/** ![754728](https://htmlcolors.com/color-image/754728.png) */
		NET_PLAYER12_DARK = 'HUD_COLOUR_NET_PLAYER12_DARK',
		/** ![4C6575](https://htmlcolors.com/color-image/4C6575.png) */
		NET_PLAYER13_DARK = 'HUD_COLOUR_NET_PLAYER13_DARK',
		/** ![41232F](https://htmlcolors.com/color-image/41232F.png) */
		NET_PLAYER14_DARK = 'HUD_COLOUR_NET_PLAYER14_DARK',
		/** ![48473D](https://htmlcolors.com/color-image/48473D.png) */
		NET_PLAYER15_DARK = 'HUD_COLOUR_NET_PLAYER15_DARK',
		/** ![553A2F](https://htmlcolors.com/color-image/553A2F.png) */
		NET_PLAYER16_DARK = 'HUD_COLOUR_NET_PLAYER16_DARK',
		/** ![575454](https://htmlcolors.com/color-image/575454.png) */
		NET_PLAYER17_DARK = 'HUD_COLOUR_NET_PLAYER17_DARK',
		/** ![74474D](https://htmlcolors.com/color-image/74474D.png) */
		NET_PLAYER18_DARK = 'HUD_COLOUR_NET_PLAYER18_DARK',
		/** ![5D6B2D](https://htmlcolors.com/color-image/5D6B2D.png) */
		NET_PLAYER19_DARK = 'HUD_COLOUR_NET_PLAYER19_DARK',
		/** ![063D2B](https://htmlcolors.com/color-image/063D2B.png) */
		NET_PLAYER20_DARK = 'HUD_COLOUR_NET_PLAYER20_DARK',
		/** ![3D627F](https://htmlcolors.com/color-image/3D627F.png) */
		NET_PLAYER21_DARK = 'HUD_COLOUR_NET_PLAYER21_DARK',
		/** ![551E73](https://htmlcolors.com/color-image/551E73.png) */
		NET_PLAYER22_DARK = 'HUD_COLOUR_NET_PLAYER22_DARK',
		/** ![675406](https://htmlcolors.com/color-image/675406.png) */
		NET_PLAYER23_DARK = 'HUD_COLOUR_NET_PLAYER23_DARK',
		/** ![233156](https://htmlcolors.com/color-image/233156.png) */
		NET_PLAYER24_DARK = 'HUD_COLOUR_NET_PLAYER24_DARK',
		/** ![15535C](https://htmlcolors.com/color-image/15535C.png) */
		NET_PLAYER25_DARK = 'HUD_COLOUR_NET_PLAYER25_DARK',
		/** ![5D623E](https://htmlcolors.com/color-image/5D623E.png) */
		NET_PLAYER26_DARK = 'HUD_COLOUR_NET_PLAYER26_DARK',
		/** ![64707F](https://htmlcolors.com/color-image/64707F.png) */
		NET_PLAYER27_DARK = 'HUD_COLOUR_NET_PLAYER27_DARK',
		/** ![78784B](https://htmlcolors.com/color-image/78784B.png) */
		NET_PLAYER28_DARK = 'HUD_COLOUR_NET_PLAYER28_DARK',
		/** ![984C5D](https://htmlcolors.com/color-image/984C5D.png) */
		NET_PLAYER29_DARK = 'HUD_COLOUR_NET_PLAYER29_DARK',
		/** ![7C4545](https://htmlcolors.com/color-image/7C4545.png) */
		NET_PLAYER30_DARK = 'HUD_COLOUR_NET_PLAYER30_DARK',
		/** ![0A2B32](https://htmlcolors.com/color-image/0A2B32.png) */
		NET_PLAYER31_DARK = 'HUD_COLOUR_NET_PLAYER31_DARK',
		/** ![5F5F0A](https://htmlcolors.com/color-image/5F5F0A.png) */
		NET_PLAYER32_DARK = 'HUD_COLOUR_NET_PLAYER32_DARK',
		/** ![B48261](https://htmlcolors.com/color-image/B48261.png) */
		BRONZE = 'HUD_COLOUR_BRONZE',
		/** ![9699A1](https://htmlcolors.com/color-image/9699A1.png) */
		SILVER = 'HUD_COLOUR_SILVER',
		/** ![D6B563](https://htmlcolors.com/color-image/D6B563.png) */
		GOLD = 'HUD_COLOUR_GOLD',
		/** ![A6DDBE](https://htmlcolors.com/color-image/A6DDBE.png) */
		PLATINUM = 'HUD_COLOUR_PLATINUM',
		/** ![1D6499](https://htmlcolors.com/color-image/1D6499.png) */
		GANG1 = 'HUD_COLOUR_GANG1',
		/** ![D6740F](https://htmlcolors.com/color-image/D6740F.png) */
		GANG2 = 'HUD_COLOUR_GANG2',
		/** ![877D8E](https://htmlcolors.com/color-image/877D8E.png) */
		GANG3 = 'HUD_COLOUR_GANG3',
		/** ![E577B9](https://htmlcolors.com/color-image/E577B9.png) */
		GANG4 = 'HUD_COLOUR_GANG4',
		/** ![FCEFA6](https://htmlcolors.com/color-image/FCEFA6.png) */
		SAME_CREW = 'HUD_COLOUR_SAME_CREW',
		/** ![2D6EB9](https://htmlcolors.com/color-image/2D6EB9.png) */
		FREEMODE = 'HUD_COLOUR_FREEMODE',
		/** ![000000](https://htmlcolors.com/color-image/000000.png) */
		PAUSE_BG = 'HUD_COLOUR_PAUSE_BG',
		/** ![5DB6E5](https://htmlcolors.com/color-image/5DB6E5.png) */
		FRIENDLY = 'HUD_COLOUR_FRIENDLY',
		/** ![C25050](https://htmlcolors.com/color-image/C25050.png) */
		ENEMY = 'HUD_COLOUR_ENEMY',
		/** ![F0C850](https://htmlcolors.com/color-image/F0C850.png) */
		LOCATION = 'HUD_COLOUR_LOCATION',
		/** ![72CC72](https://htmlcolors.com/color-image/72CC72.png) */
		PICKUP = 'HUD_COLOUR_PICKUP',
		/** ![72CC72](https://htmlcolors.com/color-image/72CC72.png) */
		PAUSE_SINGLEPLAYER = 'HUD_COLOUR_PAUSE_SINGLEPLAYER',
		/** ![16375C](https://htmlcolors.com/color-image/16375C.png) */
		FREEMODE_DARK = 'HUD_COLOUR_FREEMODE_DARK',
		/** ![9A9A9A](https://htmlcolors.com/color-image/9A9A9A.png) */
		INACTIVE_MISSION = 'HUD_COLOUR_INACTIVE_MISSION',
		/** ![C25050](https://htmlcolors.com/color-image/C25050.png) */
		DAMAGE = 'HUD_COLOUR_DAMAGE',
		/** ![FC73C9](https://htmlcolors.com/color-image/FC73C9.png) */
		PINKLIGHT = 'HUD_COLOUR_PINKLIGHT',
		/** ![FCB131](https://htmlcolors.com/color-image/FCB131.png) */
		PM_MITEM_HIGHLIGHT = 'HUD_COLOUR_PM_MITEM_HIGHLIGHT',
		/** ![000000](https://htmlcolors.com/color-image/000000.png) */
		SCRIPT_VARIABLE = 'HUD_COLOUR_SCRIPT_VARIABLE',
		/** ![6DF7CC](https://htmlcolors.com/color-image/6DF7CC.png) */
		YOGA = 'HUD_COLOUR_YOGA',
		/** ![F16522](https://htmlcolors.com/color-image/F16522.png) */
		TENNIS = 'HUD_COLOUR_TENNIS',
		/** ![D6BD61](https://htmlcolors.com/color-image/D6BD61.png) */
		GOLF = 'HUD_COLOUR_GOLF',
		/** ![701919](https://htmlcolors.com/color-image/701919.png) */
		SHOOTING_RANGE = 'HUD_COLOUR_SHOOTING_RANGE',
		/** ![2F5C73](https://htmlcolors.com/color-image/2F5C73.png) */
		FLIGHT_SCHOOL = 'HUD_COLOUR_FLIGHT_SCHOOL',
		/** ![5DB6E5](https://htmlcolors.com/color-image/5DB6E5.png) */
		NORTH_BLUE = 'HUD_COLOUR_NORTH_BLUE',
		/** ![EA991C](https://htmlcolors.com/color-image/EA991C.png) */
		SOCIAL_CLUB = 'HUD_COLOUR_SOCIAL_CLUB',
		/** ![0B377B](https://htmlcolors.com/color-image/0B377B.png) */
		PLATFORM_BLUE = 'HUD_COLOUR_PLATFORM_BLUE',
		/** ![92C83E](https://htmlcolors.com/color-image/92C83E.png) */
		PLATFORM_GREEN = 'HUD_COLOUR_PLATFORM_GREEN',
		/** ![EA991C](https://htmlcolors.com/color-image/EA991C.png) */
		PLATFORM_GREY = 'HUD_COLOUR_PLATFORM_GREY',
		/** ![425994](https://htmlcolors.com/color-image/425994.png) */
		FACEBOOK_BLUE = 'HUD_COLOUR_FACEBOOK_BLUE',
		/** ![000000](https://htmlcolors.com/color-image/000000.png) */
		INGAME_BG = 'HUD_COLOUR_INGAME_BG',
		/** ![72CC72](https://htmlcolors.com/color-image/72CC72.png) */
		DARTS = 'HUD_COLOUR_DARTS',
		/** ![A44CF2](https://htmlcolors.com/color-image/A44CF2.png) */
		WAYPOINT = 'HUD_COLOUR_WAYPOINT',
		/** ![65B4D4](https://htmlcolors.com/color-image/65B4D4.png) */
		MICHAEL = 'HUD_COLOUR_MICHAEL',
		/** ![ABEDAB](https://htmlcolors.com/color-image/ABEDAB.png) */
		FRANKLIN = 'HUD_COLOUR_FRANKLIN',
		/** ![FFA357](https://htmlcolors.com/color-image/FFA357.png) */
		TREVOR = 'HUD_COLOUR_TREVOR',
		/** ![F0F0F0](https://htmlcolors.com/color-image/F0F0F0.png) */
		GOLF_P1 = 'HUD_COLOUR_GOLF_P1',
		/** ![EBEF1E](https://htmlcolors.com/color-image/EBEF1E.png) */
		GOLF_P2 = 'HUD_COLOUR_GOLF_P2',
		/** ![FF950E](https://htmlcolors.com/color-image/FF950E.png) */
		GOLF_P3 = 'HUD_COLOUR_GOLF_P3',
		/** ![F63CA1](https://htmlcolors.com/color-image/F63CA1.png) */
		GOLF_P4 = 'HUD_COLOUR_GOLF_P4',
		/** ![D2A6F9](https://htmlcolors.com/color-image/D2A6F9.png) */
		WAYPOINTLIGHT = 'HUD_COLOUR_WAYPOINTLIGHT',
		/** ![522679](https://htmlcolors.com/color-image/522679.png) */
		WAYPOINTDARK = 'HUD_COLOUR_WAYPOINTDARK',
		/** ![000000](https://htmlcolors.com/color-image/000000.png) */
		PANEL_LIGHT = 'HUD_COLOUR_PANEL_LIGHT',
		/** ![486774](https://htmlcolors.com/color-image/486774.png) */
		MICHAEL_DARK = 'HUD_COLOUR_MICHAEL_DARK',
		/** ![557655](https://htmlcolors.com/color-image/557655.png) */
		FRANKLIN_DARK = 'HUD_COLOUR_FRANKLIN_DARK',
		/** ![7F512B](https://htmlcolors.com/color-image/7F512B.png) */
		TREVOR_DARK = 'HUD_COLOUR_TREVOR_DARK',
		/** ![F0C850](https://htmlcolors.com/color-image/F0C850.png) */
		OBJECTIVE_ROUTE = 'HUD_COLOUR_OBJECTIVE_ROUTE',
		/** ![000000](https://htmlcolors.com/color-image/000000.png) */
		PAUSEMAP_TINT = 'HUD_COLOUR_PAUSEMAP_TINT',
		/** ![646464](https://htmlcolors.com/color-image/646464.png) */
		PAUSE_DESELECT = 'HUD_COLOUR_PAUSE_DESELECT',
		/** ![2D6EB9](https://htmlcolors.com/color-image/2D6EB9.png) */
		PM_WEAPONS_PURCHASABLE = 'HUD_COLOUR_PM_WEAPONS_PURCHASABLE',
		/** ![F0F0F0](https://htmlcolors.com/color-image/F0F0F0.png) */
		PM_WEAPONS_LOCKED = 'HUD_COLOUR_PM_WEAPONS_LOCKED',
		/** ![000000](https://htmlcolors.com/color-image/000000.png) */
		END_SCREEN_BG = 'HUD_COLOUR_END_SCREEN_BG',
		/** ![E03232](https://htmlcolors.com/color-image/E03232.png) */
		CHOP = 'HUD_COLOUR_CHOP',
		/** ![000000](https://htmlcolors.com/color-image/000000.png) */
		PAUSEMAP_TINT_HALF = 'HUD_COLOUR_PAUSEMAP_TINT_HALF',
		/** ![004785](https://htmlcolors.com/color-image/004785.png) */
		NORTH_BLUE_OFFICIAL = 'HUD_COLOUR_NORTH_BLUE_OFFICIAL',
		/** ![000000](https://htmlcolors.com/color-image/000000.png) */
		SCRIPT_VARIABLE_2 = 'HUD_COLOUR_SCRIPT_VARIABLE_2',
		/** ![217625](https://htmlcolors.com/color-image/217625.png) */
		H = 'HUD_COLOUR_H',
		/** ![256628](https://htmlcolors.com/color-image/256628.png) */
		HDARK = 'HUD_COLOUR_HDARK',
		/** ![EA991C](https://htmlcolors.com/color-image/EA991C.png) */
		T = 'HUD_COLOUR_T',
		/** ![E18C08](https://htmlcolors.com/color-image/E18C08.png) */
		TDARK = 'HUD_COLOUR_TDARK',
		/** ![142800](https://htmlcolors.com/color-image/142800.png) */
		HSHARD = 'HUD_COLOUR_HSHARD',
		/** ![30FFFF](https://htmlcolors.com/color-image/30FFFF.png) */
		CONTROLLER_MICHAEL = 'HUD_COLOUR_CONTROLLER_MICHAEL',
		/** ![30FF00](https://htmlcolors.com/color-image/30FF00.png) */
		CONTROLLER_FRANKLIN = 'HUD_COLOUR_CONTROLLER_FRANKLIN',
		/** ![B05000](https://htmlcolors.com/color-image/B05000.png) */
		CONTROLLER_TREVOR = 'HUD_COLOUR_CONTROLLER_TREVOR',
		/** ![7F0000](https://htmlcolors.com/color-image/7F0000.png) */
		CONTROLLER_CHOP = 'HUD_COLOUR_CONTROLLER_CHOP',
		/** ![35A6E0](https://htmlcolors.com/color-image/35A6E0.png) */
		VIDEO_EDITOR_VIDEO = 'HUD_COLOUR_VIDEO_EDITOR_VIDEO',
		/** ![A24F9D](https://htmlcolors.com/color-image/A24F9D.png) */
		VIDEO_EDITOR_AUDIO = 'HUD_COLOUR_VIDEO_EDITOR_AUDIO',
		/** ![68C08D](https://htmlcolors.com/color-image/68C08D.png) */
		VIDEO_EDITOR_TEXT = 'HUD_COLOUR_VIDEO_EDITOR_TEXT',
		/** ![1D6499](https://htmlcolors.com/color-image/1D6499.png) */
		HB_BLUE = 'HUD_COLOUR_HB_BLUE',
		/** ![EA991C](https://htmlcolors.com/color-image/EA991C.png) */
		HB_YELLOW = 'HUD_COLOUR_HB_YELLOW',
		/** ![F0A001](https://htmlcolors.com/color-image/F0A001.png) */
		VIDEO_EDITOR_SCORE = 'HUD_COLOUR_VIDEO_EDITOR_SCORE',
		/** ![3B2239](https://htmlcolors.com/color-image/3B2239.png) */
		VIDEO_EDITOR_AUDIO_FADEOUT = 'HUD_COLOUR_VIDEO_EDITOR_AUDIO_FADEOUT',
		/** ![294435](https://htmlcolors.com/color-image/294435.png) */
		VIDEO_EDITOR_TEXT_FADEOUT = 'HUD_COLOUR_VIDEO_EDITOR_TEXT_FADEOUT',
		/** ![523A0A](https://htmlcolors.com/color-image/523A0A.png) */
		VIDEO_EDITOR_SCORE_FADEOUT = 'HUD_COLOUR_VIDEO_EDITOR_SCORE_FADEOUT',
		/** ![256628](https://htmlcolors.com/color-image/256628.png) */
		HEIST_BACKGROUND = 'HUD_COLOUR_HEIST_BACKGROUND',
		/** ![F0C850](https://htmlcolors.com/color-image/F0C850.png) */
		VIDEO_EDITOR_AMBIENT = 'HUD_COLOUR_VIDEO_EDITOR_AMBIENT',
		/** ![504622](https://htmlcolors.com/color-image/504622.png) */
		VIDEO_EDITOR_AMBIENT_FADEOUT = 'HUD_COLOUR_VIDEO_EDITOR_AMBIENT_FADEOUT',
		/** ![FF8555](https://htmlcolors.com/color-image/FF8555.png) */
		VIDEO_EDITOR_AMBIENT_DARK = 'HUD_COLOUR_VIDEO_EDITOR_AMBIENT_DARK',
		/** ![FFC2AA](https://htmlcolors.com/color-image/FFC2AA.png) */
		VIDEO_EDITOR_AMBIENT_LIGHT = 'HUD_COLOUR_VIDEO_EDITOR_AMBIENT_LIGHT',
		/** ![FF8555](https://htmlcolors.com/color-image/FF8555.png) */
		VIDEO_EDITOR_AMBIENT_MID = 'HUD_COLOUR_VIDEO_EDITOR_AMBIENT_MID',
		/** ![F0C850](https://htmlcolors.com/color-image/F0C850.png) */
		LOW_FLOW = 'HUD_COLOUR_LOW_FLOW',
		/** ![7E6B29](https://htmlcolors.com/color-image/7E6B29.png) */
		LOW_FLOW_DARK = 'HUD_COLOUR_LOW_FLOW_DARK',
		/** ![F79F7B](https://htmlcolors.com/color-image/F79F7B.png) */
		G1 = 'HUD_COLOUR_G1',
		/** ![E286BB](https://htmlcolors.com/color-image/E286BB.png) */
		G2 = 'HUD_COLOUR_G2',
		/** ![EFEE97](https://htmlcolors.com/color-image/EFEE97.png) */
		G3 = 'HUD_COLOUR_G3',
		/** ![71A9AF](https://htmlcolors.com/color-image/71A9AF.png) */
		G4 = 'HUD_COLOUR_G4',
		/** ![A08CC1](https://htmlcolors.com/color-image/A08CC1.png) */
		G5 = 'HUD_COLOUR_G5',
		/** ![8DCEA7](https://htmlcolors.com/color-image/8DCEA7.png) */
		G6 = 'HUD_COLOUR_G6',
		/** ![B5D6EA](https://htmlcolors.com/color-image/B5D6EA.png) */
		G7 = 'HUD_COLOUR_G7',
		/** ![B29084](https://htmlcolors.com/color-image/B29084.png) */
		G8 = 'HUD_COLOUR_G8',
		/** ![008472](https://htmlcolors.com/color-image/008472.png) */
		G9 = 'HUD_COLOUR_G9',
		/** ![D85575](https://htmlcolors.com/color-image/D85575.png) */
		G10 = 'HUD_COLOUR_G10',
		/** ![1E6498](https://htmlcolors.com/color-image/1E6498.png) */
		G11 = 'HUD_COLOUR_G11',
		/** ![2BB575](https://htmlcolors.com/color-image/2BB575.png) */
		G12 = 'HUD_COLOUR_G12',
		/** ![E98D4F](https://htmlcolors.com/color-image/E98D4F.png) */
		G13 = 'HUD_COLOUR_G13',
		/** ![89D2D7](https://htmlcolors.com/color-image/89D2D7.png) */
		G14 = 'HUD_COLOUR_G14',
		/** ![867D8D](https://htmlcolors.com/color-image/867D8D.png) */
		G15 = 'HUD_COLOUR_G15',
		/** ![6D2221](https://htmlcolors.com/color-image/6D2221.png) */
		ADVERSARY = 'HUD_COLOUR_ADVERSARY',
		/** ![FF0000](https://htmlcolors.com/color-image/FF0000.png) */
		DEGEN_RED = 'HUD_COLOUR_DEGEN_RED',
		/** ![FFFF00](https://htmlcolors.com/color-image/FFFF00.png) */
		DEGEN_YELLOW = 'HUD_COLOUR_DEGEN_YELLOW',
		/** ![00FF00](https://htmlcolors.com/color-image/00FF00.png) */
		DEGEN_GREEN = 'HUD_COLOUR_DEGEN_GREEN',
		/** ![00FFFF](https://htmlcolors.com/color-image/00FFFF.png) */
		DEGEN_CYAN = 'HUD_COLOUR_DEGEN_CYAN',
		/** ![0000FF](https://htmlcolors.com/color-image/0000FF.png) */
		DEGEN_BLUE = 'HUD_COLOUR_DEGEN_BLUE',
		/** ![FF00FF](https://htmlcolors.com/color-image/FF00FF.png) */
		DEGEN_MAGENTA = 'HUD_COLOUR_DEGEN_MAGENTA',
		/** ![2688EA](https://htmlcolors.com/color-image/2688EA.png) */
		STUNT_1 = 'HUD_COLOUR_STUNT_1',
		/** ![E03232](https://htmlcolors.com/color-image/E03232.png) */
		STUNT_2 = 'HUD_COLOUR_STUNT_2',
		/** ![9AB236](https://htmlcolors.com/color-image/9AB236.png) */
		SPECIAL_RACE_SERIES = 'HUD_COLOUR_SPECIAL_RACE_SERIES',
		/** ![5D6B2D](https://htmlcolors.com/color-image/5D6B2D.png) */
		SPECIAL_RACE_SERIES_DARK = 'HUD_COLOUR_SPECIAL_RACE_SERIES_DARK',
		/** ![CEA90D](https://htmlcolors.com/color-image/CEA90D.png) */
		CS = 'HUD_COLOUR_CS',
		/** ![675406](https://htmlcolors.com/color-image/675406.png) */
		CS_DARK = 'HUD_COLOUR_CS_DARK',
		/** ![009797](https://htmlcolors.com/color-image/009797.png) */
		TECH_GREEN = 'HUD_COLOUR_TECH_GREEN',
		/** ![057771](https://htmlcolors.com/color-image/057771.png) */
		TECH_GREEN_DARK = 'HUD_COLOUR_TECH_GREEN_DARK',
		/** ![970000](https://htmlcolors.com/color-image/970000.png) */
		TECH_RED = 'HUD_COLOUR_TECH_RED',
		/** ![002828](https://htmlcolors.com/color-image/002828.png) */
		TECH_GREEN_VERY_DARK = 'HUD_COLOUR_TECH_GREEN_VERY_DARK'
	}

	/** [https://wiki.rage.mp/index.php?title=HUD_Components](https://wiki.rage.mp/index.php?title=HUD_Components) */
	const enum Component {
		HUD = 0,
		WANTED_STARS = 1,
		WEAPON_ICON = 2,
		CASH = 3,
		MP_CASH = 4,
		MP_MESSAGE = 5,
		VEHICLE_NAME = 6,
		AREA_NAME = 7,
		VEHICLE_CLASS = 8,
		STREET_NAME = 9,
		HELP_TEXT = 10,
		FLOATING_HELP_TEXT_1 = 11,
		FLOATING_HELP_TEXT_2 = 12,
		CASH_CHANGE = 13,
		RETICLE = 14,
		SUBTITLE_TEXT = 15,
		RADIO_STATIONS = 16,
		SAVING_GAME = 17,
		GAME_STREAM = 18,
		WEAPON_WHEEL = 19,
		WEAPON_WHEEL_STATS = 20
	}
}

declare namespace RageEnums {
	export import HudComponent = RageEnums.Hud.Component;
}
